name: Setup
description: 'Setup dependencies and run tests'

inputs:
  github_token:
    description: 'Github token for coveralls'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '10'
        registry-url: 'https://registry.npmjs.org'

    - name: Install yarn
      shell: bash
      run: npm install -g yarn

    - name: Install dependencies
      shell: bash
      run: yarn install

    - name: Run tests
      shell: bash
      run: yarn test:cover

    - name: Run coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}