name: Publish

on: pull_request
#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dependencies and run tests
        uses: ./.github/actions/setup-dependencies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch npm token
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault.jimdo-platform.net
          method: jwt
          role: github_jimdo
          exportEnv: false
          secrets: |
            secret/creator/npm-publish-token NPM_TOKEN | NPM_PUBLISH_TOKEN;

      - name: Get latest tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Publish
        run: |
          npm config set git-tag-version=false
          npm version ${{ steps.latest_tag.outputs.tag }}
          npm publish
        env:
          NPM_TOKEN: ${{ steps.secrets.outputs.NPM_PUBLISH_TOKEN }}

  slack-workflow-status:
    name: Post workflow status to Slack
    needs:
      - publish
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we need to notify
        uses: Jimdo/should-i-notify-action@main
        id: should_notify
        with:
          branch: master
          needs_context: ${{ toJson(needs) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack workflow notification
        uses: Gamesight/slack-workflow-status@master
        if: steps.should_notify.outputs.should_send_message == 'yes'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: 'creator-deployments'
          name: 'serverless-dotenv'